FROM nfcore/base:1.9
LABEL authors="Kaiyu Zhu, Xiaoqiong Bao, Zeyu Zhong" \
    description="Docker image containing all software requirements for the MeRIPseqPipe pipeline"

# Install the conda environment
COPY environment.yml /

RUN conda env create -f /environment.yml && conda clean -a

RUN conda create -n umitools -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge python=3.7.8 umi_tools=1.1.2 && conda clean -a

# install subread
RUN conda create -n multiqc -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge python=3.7.8 multiqc=1.7 && conda clean -a

RUN conda env export --name meripseqpipe-1.0dev > meripseqpipe-1.0dev.yml
ENV PATH /mspc:$PATH
ENV PATH /opt/conda/bin:$PATH
ENV PATH /opt/conda/envs/umitools/bin/:$PATH
ENV PATH /opt/conda/envs/multiqc/bin/:$PATH
ENV PATH /opt/conda/envs/meripseqpipe-1.0dev/bin:$PATH


# install MATK
RUN wget https://github.com/kingzhuky/MATK_backup/releases/download/v0.1dev/MATK-1.0.jar

# # install QNB
RUN conda install -c bioconda bioconductor-rsamtools
RUN conda install -c bioconda bioconductor-genomicfeatures
# RUN conda install -c bioconda bioconductor-exomepeak
# RUN wget https://cran.r-project.org/src/contrib/Archive/QNB/QNB_1.1.11.tar.gz && \ 
#     R CMD INSTALL QNB_1.1.11.tar.gz && \
#     rm QNB_1.1.11.tar.gz

# install MeTDiff
# RUN conda install -c bioconda bioconductor-rtracklayer
RUN git clone https://github.com/compgenomics/MeTDiff.git && \
    R CMD build MeTDiff/ && \
    R CMD INSTALL MeTDiff_1.0.tar.gz && \
    rm -rf MeTDiff*

# install MeTPeak
RUN git clone https://github.com/compgenomics/MeTPeak.git && \
    R CMD build MeTPeak/ && \
    R CMD INSTALL MeTPeak_1.0.0.tar.gz && \
    rm -rf MeTPeak*

# install MSPC
RUN conda install -y unzip 
RUN wget -O mspc.zip "https://github.com/Genometric/MSPC/releases/download/v5.4.0/linux-x64.zip" && \
    unzip mspc.zip -d mspc && \
    chmod 775 mspc/mspc && \ 
    rm mspc.zip
